# Generated by Django 4.2 on 2023-06-13 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a club's name", max_length=50, unique=True, verbose_name='Jméno klubu')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Kluby',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Fotbalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter footballer's name", max_length=50, unique=True, verbose_name='Jméno fotbalisty')),
                ('surname', models.CharField(default='', help_text="Enter footballer's surname", max_length=50, unique=True, verbose_name='Příjmení fotbalisty')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Datum narození fotbalisty')),
                ('description', models.CharField(help_text="Enter footballer's description", max_length=255, null=True, verbose_name='Popis fotbalisty')),
                ('rate', models.IntegerField(help_text="Enter a footballer's rating", null=True, verbose_name='Hodnocení fotbalisty')),
                ('poster', models.ImageField(null=True, upload_to='', verbose_name='Fotka fotbalisty')),
                ('klub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.klub')),
            ],
            options={
                'verbose_name': 'Fotbalista',
                'verbose_name_plural': 'Fotbalisti',
                'ordering': ['surname', 'name'],
            },
        ),
    ]
